import {
  BsGithub,
  BsLinkedin,
  BsFiletypePdf,
  BsThreeDots,
  BsSunFill,
  BsPersonWorkspace,
  BsChatSquareTextFill,
  BsCodeSquare,
  BsMortarboardFill,
  BsTvFill,
  BsFillMoonStarsFill,
  BsAlphabet,
  BsArrowUpRight,
} from 'react-icons/bs';

export const Icons = {
  Github: BsGithub,
  LinkedIn: BsLinkedin,
  External: BsArrowUpRight,
  Sidebar: BsThreeDots,
  System: BsTvFill,
  Sun: BsSunFill,
  Moon: BsFillMoonStarsFill,
  About: BsChatSquareTextFill,
  Experience: BsPersonWorkspace,
  Projects: BsCodeSquare,
  Skills: BsAlphabet,
  Education: BsMortarboardFill,
};
